version: '3'
services:
  earthserv:
    build: .
    ports:
      - '4243:4243'
    volumes:
      - earthserv-identity:/app/identity
    env_file:
      - .env
    restart: unless-stopped

volumes:
  earthserv-identity:
