# Release: https://github.com/zenopie/earth-browser/releases/tag/v0.1.2
# Workflow URL: https://github.com/zenopie/earth-browser/actions/runs/23603077622
# Commit: https://github.com/zenopie/earth-browser/commit/abb8a4003b9770173b88454ea4ae780fd1b15449
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-browser@sha256:ca6e0ce209ec56c19d19e6df830e992f3c54aeb9c95e887b3811b0935293c460
    ports:
      - '4243:4243'
