# Release: https://github.com/zenopie/earth-browser/releases/tag/v0.1.3
# Workflow URL: https://github.com/zenopie/earth-browser/actions/runs/23612046268
# Commit: https://github.com/zenopie/earth-browser/commit/61d7b7c219133413fa6d8b4a97efd31f33f0ff72
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-browser@sha256:066f903f0a19ff1d1044abaeb211bec08f65e4b222c2ddfb903eb97c6743b7a1
    ports:
      - '4243:4243'
